import type { Metadata } from 'next'
import Provider from '../components/Provider'
import '../styles/style.scss'
import { ConfigProvider } from 'antd';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: '#4A4E57',
              colorInfo: '#A3A6AB',
              borderRadius: 2,
              fontFamily:  'Roboto',
            },
          }}
        >
          <Provider>
            {children}
          </Provider>
        </ConfigProvider>
      </body>
    </html>
  )
}
